url: https://tanianazare.com
baseurl: 

# Site settings
title: Tan Nazare | Music Theory
email: tannazaremusic@gmail.com
description: Music theory graduate student at McGill University. Research in non-Western pop music. Singer, tutor. BMus Hons (Edin), MA Music Theory (McGill).


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/tannazare/
  - title: twitter
    url: https://twitter.com/tannazare
  - title: wordpress
    url: http://washingdishes.home.blog/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-sitemap