url: https://y7kim.github.io
baseurl: 

# Site settings
title: Tania Nazare
email: tania.nazare@gmail.com
description: SOPRANO SINGER // TEACHER


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/nazaretania/
  - title: linkedin
    url: https://www.linkedin.com/in/tanianazare/
  - title: wordpress
    url: http://washingdishes.home.blog/

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
